/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectContent: typeof import('reka-ui')['SelectContent']
    SelectItem: typeof import('reka-ui')['SelectItem']
    SelectItemText: typeof import('reka-ui')['SelectItemText']
    SelectPortal: typeof import('reka-ui')['SelectPortal']
    SelectRoot: typeof import('reka-ui')['SelectRoot']
    SelectTrigger: typeof import('reka-ui')['SelectTrigger']
    SelectValue: typeof import('reka-ui')['SelectValue']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SelectContent: typeof import('reka-ui')['SelectContent']
  const SelectItem: typeof import('reka-ui')['SelectItem']
  const SelectItemText: typeof import('reka-ui')['SelectItemText']
  const SelectPortal: typeof import('reka-ui')['SelectPortal']
  const SelectRoot: typeof import('reka-ui')['SelectRoot']
  const SelectTrigger: typeof import('reka-ui')['SelectTrigger']
  const SelectValue: typeof import('reka-ui')['SelectValue']
}