name: Create Release on Tag Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

        # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 9
          run_install: false

      # Get pnpm store directory
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # Setup pnpm cache
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: build
        run: pnpm buildAll

      - name: git config
        run: |
          git config --global user.email "admin@shenzilong.cn"
          git config --global user.name "崮生"

      - name: Deploy vite-plugin-siyuan
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          git clone --quiet --branch=main https://x-access-token:${DEPLOY_KEY}@github.com/2234839/vite-plugin-siyuan.git main
          cd main
          rm -rf ./* && cp -R ../dist/vite-plugin-siyuan/. .
          mkdir -p ./.github/workflows/
          cp ../releaseRepo.yml ./.github/workflows/release.yml
          tree
          export CURRENT_VERSION=$(cat plugin.json | jq -r '.version')
          export LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` | sed 's/^v//')
          echo "CURRENT_VERSION=$CURRENT_VERSION   LATEST_TAG=$LATEST_TAG"
          if git status --porcelain | grep -q '^ M' ; then
            git add .
            git commit -m "Update dist to GitHub"
            git push -f origin main
          else
            echo "No changes  "
          fi
          if [ "$CURRENT_VERSION" != "$LATEST_TAG" ] && [[ "$CURRENT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "CURRENT_VERSION_IS_NEWER=true"
            git tag -a "v$CURRENT_VERSION" -m "Release version $CURRENT_VERSION"
            git push --tags
          else
            echo "CURRENT_VERSION_IS_NEWER=false"
          fi
          cd .. && rm -r main

      - name: Deploy audio2text_plugin_siyuan
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          git clone --quiet --branch=main https://x-access-token:${DEPLOY_KEY}@github.com/2234839/siyuan_audio2text.git main
          cd main
          rm -rf ./* && cp -R ../dist/audio2text_plugin_siyuan/. .
          mkdir -p ./.github/workflows/
          cp ../releaseRepo.yml ./.github/workflows/release.yml
          tree
          export CURRENT_VERSION=$(cat plugin.json | jq -r '.version')
          export LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` | sed 's/^v//')
          echo "CURRENT_VERSION=$CURRENT_VERSION   LATEST_TAG=$LATEST_TAG"
          if  git status --porcelain | grep -q '^ M' ; then
            git add .
            git commit -m "Update dist to GitHub"
            git push -f origin main
          else
            echo "No changes"
          fi
          if [ "$CURRENT_VERSION" != "$LATEST_TAG" ] && [[ "$CURRENT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "CURRENT_VERSION_IS_NEWER=true"
            git tag -a "v$CURRENT_VERSION" -m "Release version $CURRENT_VERSION"
            git push --tags
          else
            echo "CURRENT_VERSION_IS_NEWER=false"
          fi
          cd .. && rm -r main

      - name: Deploy sy2video-plugin-siyuan
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          git clone --quiet --branch=main https://x-access-token:${DEPLOY_KEY}@github.com/2234839/sy2video-plugin-siyuan.git main
          cd main
          rm -rf ./* && cp -R ../dist/sy2video-plugin-siyuan/. .
          mkdir -p ./.github/workflows/
          cp ../releaseRepo.yml ./.github/workflows/release.yml
          tree
          export CURRENT_VERSION=$(cat plugin.json | jq -r '.version')
          export LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` | sed 's/^v//')
          echo "CURRENT_VERSION=$CURRENT_VERSION   LATEST_TAG=$LATEST_TAG"
          if  git status --porcelain | grep -q '^ M' ; then
            git add .
            git commit -m "Update dist to GitHub"
            git push -f origin main
          else
            echo "No changes"
          fi
          if [ "$CURRENT_VERSION" != "$LATEST_TAG" ] && [[ "$CURRENT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "CURRENT_VERSION_IS_NEWER=true"
            git tag -a "v$CURRENT_VERSION" -m "Release version $CURRENT_VERSION"
            git push --tags
          else
            echo "CURRENT_VERSION_IS_NEWER=false"
          fi
          cd .. && rm -r main

      - name: Deploy OceanPress
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
            cd dist/oceanpress-siyuan-plugin
            zip -r package.zip .
            cp package.zip ../../
            echo "PACKAGE_VERSION=$(node -p -e "const p = require('./plugin.json'); p.version;")" >> $GITHUB_ENV

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "package.zip"
          tag: v${{ env.PACKAGE_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          # prerelease: true
